import React from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export default function ExplainabilityPanel({ selectedGap, shapData, telemetryData }) {
  return (
    <div className="flex flex-col gap-4">
      {/* SHAP Chart */}
      <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
        <h3 className="text-sm font-semibold mb-1 text-slate-200 underline bold">
          SHAP Feature Importance {selectedGap && `— ${selectedGap.type}`}
        </h3>
        <p className="text-xs text-slate-400 mb-4">Key reasons for flags generated by AI</p>
        <div className="h-44 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart layout="vertical" data={shapData} margin={{ left: 30 }}>
              <XAxis type="number" stroke="#244470" />
              <YAxis dataKey="feature" type="category" stroke="#94a3b8" tick={{ fontSize: 11 }} />
              <Tooltip contentStyle={{ backgroundColor: '#020811', borderColor: '#251d38' }} />
              <Bar dataKey="importance" fill="#0bc56e" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Raw Evidence Snippet */}
      <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl">
        <h3 className="text-sm font-semibold mb-2 text-slate-200">Raw Evidence Snippet</h3>
        <pre className="bg-slate-950 p-3 rounded text-xs font-mono text-emerald-400 overflow-x-auto border border-slate-800">
{`{
  "gap_id": "${selectedGap?.id || 'GAP-101'}",
  "flag_reason": "${selectedGap?.type || 'Missed Escalation'}",
  "time_elapsed": "0.4s",
  "status": "Closed without review"
}`}
        </pre>
      </div>
    </div>
  );
}